version: '3.8'

services:
  db:
    image: mysql:8.2.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:6.4.2-php8.3
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  postfixadmin:
    depends_on:
      - db
    image: postfixadmin:3.3-apache
    ports:
      - "8081:80"
    restart: always
    environment:
      POSTFIXADMIN_DB_TYPE: mysqli
      POSTFIXADMIN_DB_HOST: db
      POSTFIXADMIN_DB_USER: wordpress
      POSTFIXADMIN_DB_PASSWORD: wordpress
      POSTFIXADMIN_DB_NAME: wordpress

volumes:
  db_data: {}
